### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by hollec**
This Dockerfile works well for me to set up connections to my 8611 modem, but I'm open to feedback.

Build instructions:
`docker build -t prometheus-moto-exporter .`

### CODE REVIEW

**Comment by VxJasonxV** [comment]
I appreciate you creating this. My first few stabs at making a Dockerfile for this repository were… horribly naïve and terrible.

**Review by VxJasonxV — APPROVED** [review]
WORKS4ME!

**Comment by jamey** [comment]
@VxJasonxV It looks like you approved the change but didn't merge it - can you please merge it?  And ideally tag a Release off of this, so people can use it in Helm charts easily?

**Comment by VxJasonxV** [comment]
No, I can't merge it, I'm not a contributor on this repo.

I left a review as a peer, as an indication and concurring opinion that I make use of this as well.

**Comment by jamey** [comment]
Got it, thanks for clarifying.  @jahkeup, any chance you could merge & tag a release?

**Comment by jamey** [comment]
For anyone who was waiting and hasn't already discovered this, check out carwin/prometheus-moto-exporter - it works, including with kehao95/prometheus-exporter.

**Comment by jahkeup** [comment]
Thanks folks for the contributions here! I've merged this change in with a few additions and adjustments (see commits for details).

Much appreciated @hollec :tada:

**Comment by jahkeup** [comment]
Oh, and there's also a tagged container image building this with GitHub Actions now: 

https://github.com/jahkeup/prometheus-moto-exporter/pkgs/container/prometheus-moto-exporter/33965308?tag=v1.0.0-rc1

**Pull request merged**
